=== galaksiotech/kontoj/services.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "servicesListName": {
      "type": "string",
      "description": "Service List Name",
      "minLength": 1
    },
    "subjectMail": {
      "type": "string",
      "description": "subject of mail sent to the person with credentials, you can use variables _firstname_ and _lastname_"
    },
    "bodyMailStart": {
      "type": "string",
      "description": "start of the mail body, you can use variables _firstname_ and _lastname_, eg. 'Hello _firstname_ here are your credentials'"
    },
    "bodyMailEnd": {
      "type": "string",
      "description": "end of the mail body, you can use variables _firstname_ and _lastname_, eg. 'Greetings'"
    },
    "passwordLength": {
      "type": "number",
      "description": "length of passwords generated",
      "default": 8,
      "minimum": 8
    },
    "passwordChars": {
      "type": "string",
      "description": "caracters used for password generation, eg. ABCDEFGHIJKLMNOPQRSTUVWXYZ",
      "minLength": 10
    },
    "hideGroups": {
      "type": "array",
      "description": "a list of service groups to hide, identified by their name",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "disableGroups": {
      "type": "array",
      "description": "a list of service groups to disable, identified by their name",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "records": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "createdTime": {
            "type": "string"
          },
          "fields": {
            "type": "object",
            "properties": {
              "URL Login": {
                "type": "string",
                "description": "The URL used to connect to the service"
              },
              "Status": {
                "type": "object",
                "properties": {
                  "URL": {
                    "type" : "string",
                    "description": "The URL of the service status dashboard"
                  },
                  "iframe": {
                    "type" : "boolean",
                    "description": "If the service status can be opened in an iframe"
                  }
                }
              },
              "Service Group": {
                "type": "string",
                "description": "The Service Group, used to group services in the interface",
                "minLength": 1
              },
              "Password Notes": {
                "type": "string",
                "description": "Password notes shown in inteface and provided in mail body"
              },
              "Icon": {
                "type": "string",
                "description": "URL to an icon (it can be any browser valid image format)"
              },
              "Name": {
                "type": "string",
                "description": "Name of the service, mandatory",
                "minLength": 1
              },
              "Password Type": {
                "type": "string",
                "description": "Type of connection used, mandatory",
                "enum": [
                    "email-password",
                    "login-password",
                    "third-party"
                ]
              },
              "User Group": {
                "type": "array",
                "description": "User Group that need the service",
                "uniqueItems": true,
                "items": {
                  "type": "string"
                }
              },
              "URL Create Account": {
                "type": "string",
                "description": "URL path to create the account page on the service"
              },
              "Notes": {
                "type": "string",
                "description": "Free notes"
              },
              "Software": {
                "type": "string",
                "description": "URL to download Software"
              },
              "autofill": {
                "type": "object",
                "properties": {
                  "login": {
                    "type" : "string",
                    "description": "CSS selector for login input field, don't forget to escape double quotes"
                  },
                  "email": {
                    "type" : "string",
                    "description": "CSS selector for email input field, don't forget to escape double quotes"
                  },
                  "password": {
                    "type" : "string",
                    "description": "CSS selector for password input field, don't forget to escape double quotes"
                  },
                  "passwordconfirm": {
                    "type" : "string",
                    "description": "CSS selector for password confirm input field, don't forget to escape double quotes"
                  },
                  "firstname": {
                    "type" : "string",
                    "description": "CSS selector for firstname input field, don't forget to escape double quotes"
                  },
                  "lastname": {
                    "type" : "string",
                    "description": "CSS selector for lastname input field, don't forget to escape double quotes"
                  },
                  "fullname": {
                    "type" : "string",
                    "description": "CSS selector for fullname input field, don't forget to escape double quotes"
                  },
                  "custom": {
                    "type" : "string",
                    "description": "additionnal JavaScript code to be executed, don't forget to escape double quotes"
                  }
                }
              },
              "Config": {
                "type": "array",
                "description": "Additional config for each service, eg. 'disabled' for not loading the service, 'disableFillPassword' & 'disableFillEmail' for disabling autofill",
                "uniqueItems": true,
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "Name",
              "Password Type",
              "Service Group"
            ]
          }
        },
        "required": [
          "id",
          "fields"
        ]
      }
    }
  },
  "required": [
    "records",
    "servicesListName",
    "passwordLength",
    "passwordChars"
  ]
}

=== galaksiotech/kontoj/services.example.json
{
    "servicesListName" : "Example",
    "subjectMail" : "Credentials for _firstname_ _lastname_",
    "bodyMailStart" : "Hello _firstname_ _lastname_, here are your credentials:",
    "bodyMailEnd" : "Best regards",
    "passwordLength" : 20,
    "passwordChars" : "0123456789abcdefghijklmnopqrstuvwxyz!_-[]ABCDEFGHIJKLMNOPQRSTUVWXYZ",
	"hideGroups" : ["Software"],
	"disableGroups" : ["Social Networks"],
	"records": [{
		"id": "1",
		"createdTime": "2023-01-01T00:42:00.000Z",
		"fields": {
			"URL Login": "https://mail.google.com",
			"Status": {
				"URL": "https://www.google.com/appsstatus/dashboard/"
			},
			"Service Group": "Mail",
			"Password Notes": "(you should change it at first connection)",
			"Icon": "https://www.google.com/favicon.ico",
			"Name": "Gmail",
			"Password Type": "email-password",
			"User Group": ["standard", "admin"]
		}
	}, {
		"id": "2",
		"createdTime": "2023-01-01T00:42:00.000Z",
		"fields": {
			"URL Login": "https://outlook.live.com/owa/?nlp=1",
			"Status": {
				"URL": "https://portal.office.com/servicestatus",
				"iframe": false
			},
			"Service Group": "Mail",
			"Icon": "https://ow2.res.office365.com/owalanding/2022.9.20.02/images/favicon.ico?v=4",
			"URL Create Account": "https://outlook.live.com/owa/?nlp=1&signup=1",
			"Name": "Outlook",
			"Password Type": "email-password",
			"User Group": ["standard", "admin"]
		}
	}, {
		"id": "3",
		"createdTime": "2023-02-28T15:07:25.000Z",
		"fields": {
			"URL Login": "https://keepersecurity.eu/vault/",
			"Status": {
				"URL": "https://statuspage.keeper.io/"
			},
			"Service Group": "Software",
			"Icon": "https://www.keepersecurity.com/assets/branding/favicon-96x96.png",
			"Name": "Keeper",
			"Password Type": "email-password",
			"User Group": ["standard", "admin", "dev"]
		}
	}, {
		"id": "4",
		"createdTime": "2023-02-28T15:28:01.000Z",
		"fields": {
			"URL Login": "https://www.office.com/",
			"Status": {
				"URL": "https://status.office365.com/",
				"iframe": false
			},
			"Service Group": "Software",
			"Software": "https://c2rsetup.officeapps.live.com/c2r/download.aspx?productReleaseID=O365HomePremRetail&platform=Def&language=fr-FR",
			"Notes": "Créer un compte Outlook au préalable\n",
			"Icon": "https://res.cdn.office.net/officehub/images/content/images/favicon_m365-67350a08e8.ico",
			"URL Create Account": "https://account.microsoft.com/services/microsoft365/details",
			"Name": "Office 365",
			"Password Type": "third-party",
			"Third Party": "Microsoft",
			"User Group": ["standard", "admin"],
			"Config": ["disableFillEmail"]
		}
	}, {
		"id": "10",
		"createdTime": "2023-01-01T00:42:00.000Z",
		"fields": {
			"URL Login": "https://drive.google.com/",
			"Status": {
				"URL": "https://www.google.com/appsstatus/dashboard/"
			},
			"Service Group": "Software",
			"Icon": "https://drive.google.com/favicon.ico",
			"Name": "Google Drive",
			"Password Type": "third-party",
			"Third Party": "Google",
			"User Group": ["standard", "admin"]
		}
	}, {
		"id": "5",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://account.jetbrains.com/login",
			"Service Group": "Software",
			"Icon": "https://www.jetbrains.com/favicon.ico",
			"URL Create Account": "https://account.jetbrains.com/login",
			"Name": "PhpStorm",
			"Password Type": "email-password",
			"User Group": ["dev"]
		},
		"Config": ["disableFillPassword"]
	}, {
		"id": "6",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://gitlab.com/users/sign_in",
			"Status": {
				"URL": "https://status.gitlab.com/"
			},
			"Service Group": "Development",
			"Icon": "https://gitlab.com/favicon.ico",
			"URL Create Account": "https://gitlab.com/users/sign_up",
			"Name": "Gitlab",
			"Password Type": "email-password",
			"User Group": ["standard"],
			"autofill" : {
				"firstname" : "input[id='new_user_first_name']",
				"lastname" : "input[id='new_user_last_name']",
				"email" : "input[id='new_user_email']",
				"password" : "input[id='new_user_password']"
			}
		}
	}, {
		"id": "7",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://github.com/login",
			"Service Group": "Development",
			"Icon": "https://github.com/favicon.ico",
			"URL Create Account": "https://github.com/signup",
			"Name": "GitHub",
			"Password Type": "email-password",
			"User Group": ["standard"],
			"Config": ["disabled"]
		}
	}, {
		"id": "11",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://www.npmjs.com/login",
			"Service Group": "Development",
			"URL Create Account": "https://www.npmjs.com/signup",
			"Name": "npm",
			"Password Type": "login-password",
			"User Group": ["standard"],
			"autofill" : {
				"login" : "input[id='signup_name']",
				"email" : "input[id='signup_email']",
				"password" : "input[id='signup_password']"
			}
		}
	}, {
		"id": "8",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://twitter.com/i/flow/login",
			"Service Group": "Social Networks",
			"Icon": "https://abs.twimg.com/favicons/twitter.3.ico",
			"URL Create Account": "https://twitter.com/i/flow/signup",
			"Name": "X",
			"Password Type": "email-password",
			"User Group": ["standard"]
		}
	}, {
		"id": "9",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://www.threads.net/login",
			"Service Group": "Social Networks",
			"Icon": "https://static.cdninstagram.com/rsrc.php/v3/yV/r/_8T3PbCSTRI.png",
			"Name": "Threads",
			"Password Type": "email-password",
			"User Group": ["standard"]
		}
	}]
}

=== galaksiotech/kontoj/src/services.example.json
{
    "servicesListName" : "Example",
    "subjectMail" : "Credentials for _firstname_ _lastname_",
    "bodyMailStart" : "Hello _firstname_ _lastname_, here are your credentials:",
    "bodyMailEnd" : "",
    "passwordLength" : 20,
    "passwordChars" : "0123456789abcdefghijklmnopqrstuvwxyz!_-[]ABCDEFGHIJKLMNOPQRSTUVWXYZ",
	"hideGroups" : ["Software"],
	"disableGroups" : ["Social Networks"],
	"records": [{
		"id": "1",
		"createdTime": "2023-01-01T00:42:00.000Z",
		"fields": {
			"URL Login": "https://mail.google.com",
			"Service Group": "Mail",
			"Password Notes": "(you should change it at first connection)",
			"Icon": "https://www.google.com/favicon.ico",
			"Name": "Gmail",
			"Password Type": "email-password",
			"User Group": ["standard", "admin"]
		}
	}, {
		"id": "2",
		"createdTime": "2023-01-01T00:42:00.000Z",
		"fields": {
			"URL Login": "https://outlook.live.com/owa/?nlp=1",
			"Service Group": "Mail",
			"Icon": "https://ow2.res.office365.com/owalanding/2022.9.20.02/images/favicon.ico?v=4",
			"URL Create Account": "https://outlook.live.com/owa/?nlp=1&signup=1",
			"Name": "Outlook",
			"Password Type": "email-password",
			"User Group": ["standard", "admin"]
		}
	}, {
		"id": "3",
		"createdTime": "2023-02-28T15:07:25.000Z",
		"fields": {
			"URL Login": "https://keepersecurity.eu/vault/",
			"Service Group": "Software",
			"Icon": "https://www.keepersecurity.com/assets/branding/favicon-96x96.png",
			"Name": "Keeper",
			"Password Type": "email-password",
			"User Group": ["standard", "admin", "dev"]
		}
	}, {
		"id": "4",
		"createdTime": "2023-02-28T15:28:01.000Z",
		"fields": {
			"URL Login": "https://www.office.com/",
			"Service Group": "Software",
			"Software": "https://c2rsetup.officeapps.live.com/c2r/download.aspx?productReleaseID=O365HomePremRetail&platform=Def&language=fr-FR",
			"Notes": "Créer un compte Outlook au préalable\n",
			"Icon": "https://res.cdn.office.net/officehub/images/content/images/favicon_m365-67350a08e8.ico",
			"URL Create Account": "https://account.microsoft.com/services/microsoft365/details",
			"Name": "Office 365",
			"Password Type": "email-password",
			"User Group": ["standard", "admin"],
			"Config": ["disableFillEmail"]
		}
	}, {
		"id": "5",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://account.jetbrains.com/login",
			"Service Group": "Software",
			"Icon": "https://www.jetbrains.com/favicon.ico",
			"URL Create Account": "https://account.jetbrains.com/login",
			"Name": "PhpStorm",
			"Password Type": "email-password",
			"User Group": ["dev"]
		}
	}, {
		"id": "6",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://gitlab.com/users/sign_in",
			"Service Group": "Development",
			"Icon": "https://gitlab.com/favicon.ico",
			"URL Create Account": "https://gitlab.com/users/sign_up",
			"Name": "Gitlab",
			"Password Type": "email-password",
			"User Group": ["standard"],
			"autofill" : {
				"firstname" : "$(\"#new_user_first_name\")",
				"lastname" : "$(\"#new_user_last_name\")",
				"email" : "$(\"#new_user_email\")",
				"password" : "$(\"#new_user_password\")"
			},
			"Config": ["disableFillPassword"]
		}
	}, {
		"id": "7",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://github.com/login",
			"Service Group": "Development",
			"Icon": "https://github.com/favicon.ico",
			"URL Create Account": "https://github.com/signup",
			"Name": "GitHub",
			"Password Type": "email-password",
			"User Group": ["standard"],
			"Config": ["disabled"]
		}
	}, {
		"id": "8",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://twitter.com/i/flow/login",
			"Service Group": "Social Networks",
			"Icon": "https://abs.twimg.com/favicons/twitter.3.ico",
			"URL Create Account": "https://twitter.com/i/flow/signup",
			"Name": "X",
			"Password Type": "email-password",
			"User Group": ["standard"]
		}
	}, {
		"id": "9",
		"createdTime": "2023-02-28T15:32:20.000Z",
		"fields": {
			"URL Login": "https://www.threads.net/login",
			"Service Group": "Social Networks",
			"Icon": "https://static.cdninstagram.com/rsrc.php/v3/yV/r/_8T3PbCSTRI.png",
			"Name": "Threads",
			"Password Type": "email-password",
			"User Group": ["standard"]
		}
	}]
}
